<a href="https://colab.research.google.com/github/fortune-uwha/world_noodles_data_2022/blob/main/world_noodles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [61]:
url = "https://instantnoodles.org/en/noodles/demand/table/"
tables = pd.read_html(url)

# first table on the webpage
wina_df = tables[0]
wina_df.head()

  Unnamed: 0    Country/Region     2018     2019     2020   2021     2022
0          1  China/ Hong Kong  40250.0  41450.0  46360.0  43990  45070.0
1          2         Indonesia  12540.0  12520.0  12640.0  13270  14260.0
2          3          Viet Nam   5200.0   5440.0   7030.0   8560   8480.0
3          4             India   6060.0   6730.0   6730.0   7560   7580.0
4          5             Japan   5780.0   5630.0   5970.0   5850   5980.0

In [62]:
#little clean up
wina_df = wina_df.drop(wina_df.columns[0], axis=1)
wina_df.head()

     Country/Region     2018     2019     2020   2021     2022
0  China/ Hong Kong  40250.0  41450.0  46360.0  43990  45070.0
1         Indonesia  12540.0  12520.0  12640.0  13270  14260.0
2          Viet Nam   5200.0   5440.0   7030.0   8560   8480.0
3             India   6060.0   6730.0   6730.0   7560   7580.0
4             Japan   5780.0   5630.0   5970.0   5850   5980.0

In [63]:
wina_df['Country/Region'] = wina_df['Country/Region'].replace(['China/ Hong Kong'], 'China')
wina_df['Country/Region'] = wina_df['Country/Region'].replace(['Republic of Korea'], 'South Korea')

In [64]:
wina_df.head()

  Country/Region     2018     2019     2020   2021     2022
0          China  40250.0  41450.0  46360.0  43990  45070.0
1      Indonesia  12540.0  12520.0  12640.0  13270  14260.0
2       Viet Nam   5200.0   5440.0   7030.0   8560   8480.0
3          India   6060.0   6730.0   6730.0   7560   7580.0
4          Japan   5780.0   5630.0   5970.0   5850   5980.0

### Merge Population

In [65]:
population_df = pd.read_csv('/content/world_population.csv')
population_df = population_df[['Rank', 'CCA3', 'Country/Territory', 'Capital', 'Continent', '2022 Population']]
population_df.head()

   Rank CCA3 Country/Territory           Capital Continent  2022 Population
0    36  AFG       Afghanistan             Kabul      Asia         41128771
1   138  ALB           Albania            Tirana    Europe          2842321
2    34  DZA           Algeria           Algiers    Africa         44903225
3   213  ASM    American Samoa         Pago Pago   Oceania            44273
4   203  AND           Andorra  Andorra la Vella    Europe            79824

In [66]:
wina_df = wina_df.merge(population_df, left_on='Country/Region', right_on='Country/Territory')
wina_df

,Country/Region,2018,2019,2020,2021,2022,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population
0,China,40250.0,41450.0,46360.0,43990,45070.0,1,CHN,China,Beijing,Asia,1425887337
1,Indonesia,12540.0,12520.0,12640.0,13270,14260.0,4,IDN,Indonesia,Jakarta,Asia,275501339
2,India,6060.0,6730.0,6730.0,7560,7580.0,2,IND,India,New Delhi,Asia,1417173173
3,Japan,5780.0,5630.0,5970.0,5850,5980.0,11,JPN,Japan,Tokyo,Asia,123951692
4,Philippines,3980.0,3850.0,4470.0,4440,4290.0,13,PHL,Philippines,Manila,Asia,115559009
5,South Korea,3820.0,3900.0,4130.0,3790,3950.0,29,KOR,South Korea,Seoul,Asia,51815810
6,Thailand,3460.0,3570.0,3710.0,3630,3870.0,20,THA,Thailand,Bangkok,Asia,71697030
7,Brazil,2390.0,2420.0,2720.0,2850,2830.0,7,BRA,Brazil,Brasilia,South America,215313498
8,Nigeria,1820.0,1920.0,2460.0,2620,2790.0,6,NGA,Nigeria,Abuja,Africa,218541212
9,Russia,1850.0,1910.0,2000.0,2100,2200.0,9,RUS,Russia,Moscow,Europe,144713314
10,Nepal,1570.0,1640.0,1540.0,1590,1650.0,49,NPL,Nepal,Kathmandu,Asia,30547580
11,Malaysia,1370.0,1450.0,1570.0,1580,1550.0,45,MYS,Malaysia,Kuala Lumpur,Asia,33938221
12,Mexico,1120.0,1170.0,1160.0,1360,1510.0,10,MEX,Mexico,Mexico City,North America,127504125
13,Taiwan,830.0,830.0,870.0,900,880.0,57,TWN,Taiwan,Taipei,Asia,23893394
14,Saudi Arabia,550.0,560.0,830.0,850,870.0,41,SAU,Saudi Arabia,Riyadh,Asia,36408820
15,Myanmar,600.0,620.0,660.0,760,770.0,26,MMR,Myanmar,Nay Pyi Taw,Asia,54179306
16,South Africa,260.0,280.0,350.0,410,480.0,24,ZAF,South Africa,Pretoria,Africa,59893885
17,Egypt,220.0,280.0,350.0,400,460.0,14,EGY,Egypt,Cairo,Africa,110990103
18,Australia,410.0,420.0,440.0,450,450.0,55,AUS,Australia,Canberra,Oceania,26177413
19,Bangladesh,310.0,370.0,370.0,430,440.0,8,BGD,Bangladesh,Dhaka,Asia,171186372
20,Turkey,80.0,120.0,190.0,360,420.0,18,TUR,Turkey,Ankara,Asia,85341241
21,Cambodia,330.0,350.0,370.0,410,400.0,73,KHM,Cambodia,Phnom Penh,Asia,16767842
22,Germany,320.0,330.0,370.0,390,390.0,19,DEU,Germany,Berlin,Europe,83369843
23,Poland,310.0,310.0,330.0,340,380.0,37,POL,Poland,Warsaw,Europe,39857145
24,Kazakhstan,170.0,250.0,280.0,320,360.0,66,KAZ,Kazakhstan,Nursultan,Asia,19397998
25,Guatemala,230.0,250.0,260.0,270,280.0,68,GTM,Guatemala,Guatemala City,North America,17843908
26,Pakistan,190.0,200.0,220.0,230,240.0,5,PAK,Pakistan,Islamabad,Asia,235824862
27,Uzbekistan,170.0,210.0,210.0,210,210.0,43,UZB,Uzbekistan,Tashkent,Asia,34627652
28,Canada,190.0,190.0,190.0,200,200.0,39,CAN,Canada,Ottawa,North America,38454327
29,Sri Lanka,170.0,180.0,180.0,190,200.0,61,LKA,Sri Lanka,Colombo,Asia,21832143
30,Peru,160.0,160.0,160.0,170,170.0,44,PER,Peru,Lima,South America,34049588
31,Ethiopia,80.0,80.0,120.0,130,140.0,12,ETH,Ethiopia,Addis Ababa,Africa,123379924
32,Singapore,130.0,130.0,160.0,140,130.0,113,SGP,Singapore,Singapore,Asia,5975689
33,Kenya,50.0,60.0,80.0,100,130.0,27,KEN,Kenya,Nairobi,Africa,54027487
34,France,90.0,80.0,90.0,100,110.0,23,FRA,France,Paris,Europe,64626628
35,New Zealand,80.0,90.0,90.0,90,100.0,123,NZL,New Zealand,Wellington,Oceania,5185288
36,Spain,70.0,70.0,80.0,90,90.0,30,ESP,Spain,Madrid,Europe,47558630
37,Czech Republic,60.0,70.0,70.0,70,70.0,88,CZE,Czech Republic,Prague,Europe,10493986
38,Iran,50.0,50.0,60.0,60,70.0,17,IRN,Iran,Tehran,Asia,88550570
39,Sweden,40.0,50.0,60.0,60,60.0,87,SWE,Sweden,Stockholm,Europe,10549347
40,Netherlands,50.0,50.0,50.0,50,60.0,71,NLD,Netherlands,Amsterdam,Europe,17564014
41,Chile,30.0,30.0,20.0,50,60.0,65,CHL,Chile,Santiago,South America,19603733
42,Serbia,NaN,NaN,NaN,50,50.0,105,SRB,Serbia,Belgrade,Europe,7221365
43,Colombia,20.0,20.0,20.0,20,50.0,28,COL,Colombia,Bogota,South America,51874024
44,Italy,20.0,20.0,30.0,40,40.0,25,ITA,Italy,Rome,Europe,59037474
45,Hungary,30.0,40.0,40.0,40,40.0,94,HUN,Hungary,Budapest,Europe,9967308
46,Belgium,10.0,20.0,20.0,20,20.0,81,BEL,Belgium,Brussels,Europe,11655930
47,Denmark,20.0,20.0,10.0,10,20.0,115,DNK,Denmark,Copenhagen,Europe,5882261
48,Finland,10.0,20.0,20.0,20,20.0,118,FIN,Finland,Helsinki,Europe,5540745
49,Switzerland,10.0,10.0,10.0,10,20.0,101,CHE,Switzerland,Bern,Europe,8740472
50,Argentina,10.0,10.0,0.0,20,10.0,33,ARG,Argentina,Buenos Aires,South America,45510318
51,Costa Rica,10.0,10.0,10.0,20,10.0,124,CRI,Costa Rica,San José,North America,5180829
52,Ukraine,320.0,340.0,320.0,350,NaN,38,UKR,Ukraine,Kiev,Europe,39701739

In [67]:
wina_df.to_csv("noodles.csv", index=False)